In [1]:
import numpy as np

print("---- Problem 1: Array Creation ----")

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2,2))
print("Empty array 2x2:\n", empty_array)

# 2. Initialize an all ones array with size 4x2
ones_array = np.ones((4,2))
print("All ones array 4x2:\n", ones_array)

# 3. Array with given shape and fill value
filled_array = np.full((3,3), 7)  # 3x3 array filled with 7
print("Filled array 3x3 with 7:\n", filled_array)

# 4. Array of zeros like another array
zeros_like_array = np.zeros_like(filled_array)
print("Zeros like filled_array:\n", zeros_like_array)

# 5. Array of ones like another array
ones_like_array = np.ones_like(filled_array)
print("Ones like filled_array:\n", ones_like_array)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
array_from_list = np.array(new_list)
print("Array from list:", array_from_list)


---- Problem 1: Array Creation ----
Empty array 2x2:
 [[3.53077125e-315 0.00000000e+000]
 [4.94065646e-324 6.65686012e-310]]
All ones array 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Filled array 3x3 with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros like filled_array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
Ones like filled_array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Array from list: [1 2 3 4]


In [2]:
print("\n---- Problem 2: Array Manipulation ----")

# 1. Array with values ranging from 10 to 49
arr_range = np.arange(10,50)
print("Array 10 to 49:\n", arr_range)

# 2. 3x3 matrix with values from 0 to 8
matrix_3x3 = np.arange(9).reshape(3,3)
print("3x3 matrix 0-8:\n", matrix_3x3)

# 3. 3x3 identity matrix
identity_matrix = np.eye(3)
print("Identity matrix 3x3:\n", identity_matrix)

# 4. Random array of size 30 and mean
rand_array = np.random.random(30)
print("Mean of random array:", rand_array.mean())

# 5. 10x10 random array, min and max
rand_10x10 = np.random.random((10,10))
print("Min:", rand_10x10.min(), "Max:", rand_10x10.max())

# 6. Zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("Zero array with 5th element as 1:\n", zero_array)

# 7. Reverse array arr = [1,2,0,0,4,0]
arr = np.array([1,2,0,0,4,0])
print("Reversed array:", arr[::-1])

# 8. 2D array with 1 on border, 0 inside (5x5 example)
border_array = np.ones((5,5))
border_array[1:-1, 1:-1] = 0
print("2D border array:\n", border_array)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8,8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 checkerboard pattern:\n", checkerboard)



---- Problem 2: Array Manipulation ----
Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 matrix 0-8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Identity matrix 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean of random array: 0.42777566654597393
Min: 0.003984435946602138 Max: 0.9986144523641436
Zero array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reversed array: [0 4 0 0 2 1]
2D border array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
8x8 checkerboard pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [3]:
print("\n---- Problem 3: Array Operations ----")

# Arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add x+y
print("x + y =\n", x+y)

# 2. Subtract x-y
print("x - y =\n", x-y)

# 3. Multiply array with integer
print("x * 3 =\n", x*3)

# 4. Square each element
print("x squared =\n", x**2)

# 5. Dot product
print("v . w =", np.dot(v,w))
print("x . v =", np.dot(x,v))
print("x . y =", np.dot(x,y))

# 6. Concatenate x and y along row and v and w along column
print("Concatenate x and y along row:\n", np.concatenate((x,y), axis=0))
print("Concatenate v and w along column:\n", np.concatenate((v,w), axis=0))  # 1D arrays, axis ignored

# 7. Concatenate x and v -> will raise error
try:
    np.concatenate((x,v))
except ValueError as e:
    print("Error concatenating x and v:", e)



---- Problem 3: Array Operations ----
x + y =
 [[ 6  8]
 [10 13]]
x - y =
 [[-4 -4]
 [-4 -3]]
x * 3 =
 [[ 3  6]
 [ 9 15]]
x squared =
 [[ 1  4]
 [ 9 25]]
v . w = 219
x . v = [29 77]
x . y = [[19 22]
 [50 58]]
Concatenate x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
 [ 9 10 11 12]
Error concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [4]:
print("\n---- Problem 4: Matrix Operations ----")

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
print("A * A_inv =\n", np.dot(A,A_inv))  # Should be identity

# 2. Prove AB != BA
AB = np.dot(A,B)
BA = np.dot(B,A)
print("AB =\n", AB)
print("BA =\n", BA)

# 3. Prove (AB)^T = B^T A^T
print("(AB)^T =\n", AB.T)
print("B^T A^T =\n", np.dot(B.T,A.T))

# 4. Solve system of linear equations
# Equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

A_eq = np.array([[2,-3,1],
                 [1,-1,2],
                 [3,1,-1]])
B_eq = np.array([-1,-3,9])

# Solve using np.linalg.solve
X = np.linalg.solve(A_eq, B_eq)
print("Solution of the system [x,y,z]:", X)



---- Problem 4: Matrix Operations ----
A * A_inv =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
Solution of the system [x,y,z]: [ 2.  1. -2.]
